site_name: lgbsttracker
site_description: lgbsttracker
site_url: https://github.com/py4mac/lgbsttracker

theme:
    name: 'material'
    palette:
      primary: 'teal'
      accent: 'amber'
    logo: 'img/icon-white.svg'
    favicon: 'img/favicon.png'

repo_name: py4mac/lgbsttracker
repo_url: https://github.com/py4mac/lgbsttracker
edit_uri: ''

nav:
    - Main: 'index.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra